---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alimjan.
--- DateTime: 2026/7/24 15:15
---

local key = KEYS[1] -- 操作的 Redis Key
local followUserId = ARGV[1] -- 关注的用户ID
local timestamp = ARGV[2] -- 时间戳
local expireSeconds = ARGV[3] -- 过期时间（秒）

-- ZADD 添加关注关系
redis.call('ZADD', key, timestamp, followUserId)
redis.call('EXPIRE', key,expireSeconds)
return 0